export enum MaterialsEnum {
    ZIRCÔNIA_IMPLANTE = "ZIRCÔNIA IMPLANTE",
    ZIRCÔNIA_DENTE = "ZIRCÔNIA DENTE",
    EMAX_CAD = "E-MAX CAD",
    LENTE_EMAX_CAD = "LENTE E-MAX CAD",
    PLACA_MIORRELAXANTE = "PLACA MIORRELAXANTE",
    PMMA = "PMMA",
    REAJUSTE = "REAJUSTE",
}